export const GET_CATEGORYS = "GET_CATEGORYS";
export const GET_CATEGORYS_SUCCESS = "GET_CATEGORYS_SUCCESS";
export const POST_CATEGORY = "POST_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const GET_CATEGORYS_IS_PUBLIC = 'GET_CATEGORYS_IS_PUBLIC';

export const EDITING_ITEM = "EDITING_ITEM";
export const RESET_ITEM_EDITING = "RESET_ITEM_EDITING";

export const GET_ARTICLES = "GET_ARTICLES";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPDATE_STATUS_ARTICLE = "UPDATE_STATUS_ARTICLE";