export const GET_CATEGORYS = "GET_CATEGORYS";
export const GET_CATEGORYS_SUCCESS = "GET_CATEGORYS_SUCCESS";

export const POST_CATEGORY = "POST_CATEGORY";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_ERROR = "POST_CATEGORY_ERROR";