export const GET_CATEGORYS = "GET_CATEGORYS";
export const GET_CATEGORYS_SUCCESS = "GET_CATEGORYS_SUCCESS";

export const POST_CATEGORY = "POST_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const RESET_ITEM_EDITING = "RESET_ITEM_EDITING";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";